version: "3.3"

services:
  dev:
      stdin_open: true
      tty: true
      build: .
      image: continuumio/miniconda3
      expose:
        - "9999"
      # environment:
      #   - test=test
      volumes:
        - ./src/:/root/src/:rw
        - ./data/:/root/data/:rw
        - ./nbs/:/root/nbs/:rw
        # keep in sync with deploy/docker-entrypoint.d/30-copy-static-data.sh
        - source: static
          target: /opt/conda
          type: volume
          volume:
            nocopy: true
volumes:
  static: {}